version: '3'

services:
  app:
    container_name: telegram-socket-bot_app
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
        mongo:
            condition: service_started
        mysql:
            condition: service_healthy
    networks:
        - app-network
  mongo:
    container_name: telegram-socket-bot_mongo
    image: mongo:4.4.3-bionic
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
        - telegram-socket-bot_data:/data/db
    ports:
        - 27020:27017
  mysql:
    container_name: telegram-socket-bot_mysql
    image: mysql:8.0.23
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
    volumes:
        - telegram-socket-bot_logs:/var/lib/
        # Create the initial db configuration on container creation
        - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
        - 3306:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 1s
        retries: 10
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - app
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email sammy@solarwebgg.com --agree-tos --no-eff-email --force-renewal -d solarwebgg.com  -d www.solarwebgg.com

volumes:
 telegram-socket-bot_data:
  telegram-socket-bot_logs:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/sammy/telegram-socket-bot/build/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/sammy/telegram-socket-bot/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
